parameters:
    phpbbde.pastebin.path: %core.root_path%ext/phpbbde/pastebin/
    phpbbde.pastebin.geshi: %phpbbde.pastebin.path%geshi/
    tables.phpbbde.pastebin.pastebin: %core.table_prefix%pastebin
services:
    phpbbde.pastebin.functions.pastebin:
        class: phpbbde\pastebin\functions\pastebin
        arguments:
            - %phpbbde.pastebin.geshi%
    phpbbde.pastebin.controller.main:
        class: phpbbde\pastebin\controller\main
        arguments:
            - @auth
            - @cache
            - @config
            - @request
            - @dbal.conn
            - @template
            - @user
            - @controller.helper
            - @phpbbde.pastebin.functions.pastebin
            - %core.root_path%
            - %core.php_ext%
    phpbbde.pastebin.header_listener:
        class: phpbbde\pastebin\event\header_events
        arguments:
            - @auth
            - @template
            - @controller.helper
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }