parameters:
    phpbbde.pastebin.path: '%core.root_path%ext/phpbbde/pastebin/'
    phpbbde.pastebin.highlight: '%phpbbde.pastebin.path%assets/tempest/highlight/'
    phpbbde.pastebin.cron.prune_interval: 86400

imports:
    - { resource: tables.yml }

services:
    phpbbde.pastebin.functions.utility:
        class: phpbbde\pastebin\functions\utility
        arguments:
            - '%core.php_ext%'
            - '@language'

    phpbbde.pastebin.functions.pastebin:
        class: phpbbde\pastebin\functions\pastebin
        arguments:
            - '@dbal.conn'
            - '@user'
            - '%phpbbde.pastebin.tables.pastebin%'

    phpbbde.pastebin.controller.main:
        class: phpbbde\pastebin\controller\main
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@request'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@language'
            - '@files.factory'
            - '@controller.helper'
            - '@captcha.factory'
            - '@phpbbde.pastebin.functions.utility'
            - '@phpbbde.pastebin.functions.pastebin'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%phpbbde.pastebin.tables.pastebin%'

    phpbbde.pastebin.settings.acp:
        class: phpbbde\pastebin\controller\acp_pastebin_settings
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'

    phpbbde.pastebin.languages.acp:
        class: phpbbde\pastebin\controller\acp_pastebin_languages
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '%phpbbde.pastebin.tables.pastebin_langs%'

    phpbbde.pastebin.base_listener:
        class: phpbbde\pastebin\event\base_events
        arguments:
            - '@template'
            - '@controller.helper'
            - '@user'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - {name: event.listener}
    phpbbde.pastebin.acp_listener:
        class: phpbbde\pastebin\event\acp_events
        tags:
            - {name: event.listener}

    phpbbde.pastebin.cron.main:
        class: phpbbde\pastebin\cron\main
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%phpbbde.pastebin.cron.prune_interval%'
            - '%phpbbde.pastebin.tables.pastebin%'
        calls:
            - [set_name, [phpbbde.pastebin.cron.main]]
        tags:
            - {name: cron.task}

    phpbbde.pastebin.listener:
        class: phpbbde\pastebin\event\permission_listener
        arguments:
            - '@auth'
        tags:
            - { name: event.listener }